# Generated by Django 3.2.7 on 2021-11-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='ChampionName',
            field=models.CharField(default=99, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='champion',
            name='ChampionPortrait',
            field=models.CharField(default=99, max_length=500),
            preserve_default=False,
        ),
    ]
