# Generated by Django 3.2.7 on 2021-11-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20211120_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='ChampionKey',
            field=models.IntegerField(default=999),
        ),
    ]
